version: '3.1'

services:
  customer-service-api:
    container_name: customer-service-api
    image: davidjmartin/customer-service:latest
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - db-postgresql

  db-postgresql:
    container_name: db-postgresql
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydb