apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: customer-webservice
build:
  artifacts:
  - image: davidjmartin/customer-service-api
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - helm-chart/templates/customer-service-api-deployment.yaml
    - helm-chart/templates/customer-service-api-service.yaml
    - helm-chart/templates/db-postgresql-deployment.yaml
    - helm-chart/templates/db-postgresql-service.yaml
