openapi: 3.0.1
info:
  description: customer-service api docs
  title: OpenAPI definition
  version: v0
  contact:
    name: DavidJMartin
  termsOfService: DavidJMartin
servers:
  - url: 'http://localhost:8080'
    description: Generated server url
paths:
  /customers:
    get:
      summary: ''
      tags:
        - customer-controller
      operationId: getCustomers
      parameters:
        - name: page
          in: query
          required: true
          schema:
            type: integer
            format: int32
        - name: size
          in: query
          required: true
          schema:
            type: integer
            format: int32
      responses:
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorData'
        "409":
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorData'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorData'
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerPage'
    post:
      tags:
        - customer-controller
      summary: ''
      operationId: createCustomer
      responses:
        '201':
          description: CREATED
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
      description: creates a new customer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
  '/customers/{id}':
    get:
      tags:
        - customer-controller
      operationId: getCustomerById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorData'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorData'
      description: returns a customer by idó
    put:
      tags:
        - customer-controller
      summary: ''
      operationId: updateCustomerById
      description: updates a customer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorData'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorData'
    delete:
      tags:
        - customer-controller
      summary: ''
      operationId: deleteCustomerById
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
      description: deletes a customer by id
    parameters:
      - schema:
          type: integer
          format: int32
        name: id
        in: path
        required: true
        description: customer id
components:
  schemas:
    ErrorData:
      title: ErrorData
      type: object
      properties:
        url:
          type: string
        errorCode:
          type: string
        message:
          type: string
        timestamp:
          type: string
    Customer:
      title: Customer
      type: object
      properties:
        id:
          type: integer
        firstName:
          type: string
        lastName:
          type: string
        address:
          type: string
        city:
          type: string
        country:
          type: string
        email:
          type: string
        image:
          type: string
    CustomerPage:
      type: object
      properties:
        customers:
          type: array
          items:
            $ref: '#/components/schemas/Customer'
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
          format: int64