apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -c
    kompose.version: 1.25.0 (a70f80cc)
  creationTimestamp: null
  labels:
    io.kompose.service: customer-service-api
  name: customer-service-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: customer-service-api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -c
        kompose.version: 1.25.0 (a70f80cc)
      creationTimestamp: null
      labels:
        io.kompose.service: customer-service-api
    spec:
      containers:
        - image: davidjmartin/customer-service-api:latest
          imagePullPolicy: Never
          name: customer-service-api
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
