openapi: 3.0.0
info:
  title: customer-service
  version: '1.0'
servers:
  - url: 'http://localhost:8080'
paths:
  /customers:
    get:
      summary: GET /customers
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
              examples:
                example-1:
                  value:
                    - id: string
                      fname: string
                      sname: string
                      address: string
                      city: string
                      country: string
                      email: string
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
      operationId: getAllCustomers
      description: Returns all customer records.
components:
  schemas:
    Customer:
      title: Customer
      type: object
      x-examples:
        example-1:
          id: '1'
          fname: David
          sname: Martin
          address: Main St.
          city: Paris
          country: France
          email: david.martin@email.com
      description: stores customer details
      properties:
        id:
          type: number
        fname:
          type: string
        sname:
          type: string
        address:
          type: string
        city:
          type: string
        country:
          type: string
        email:
          type: string
